### ISSUE TITLE
新需求：Framework

### ISSUE THREAD

**Issue by FallenDoll** [OpenEOELOL/OpenFansite#3]
**这个新需求会解决你的痛点吗？什么痛点？**
纯原生实现各种交互以及数据管理有点麻烦

**打算怎么样**
为什么不考虑用一个框架(react vue之类的), 是出于哪方面的考虑, 体积还是开发难度?

**附言**
btw, 选择用github的page功能作为静态资源服务器是出于节省服务器资源考虑还是cdn加速?
好像国内github已经难以访问了吧, 不考虑国内的话感觉类似[vercel](https://vercel.com/) 这样的平台更好用一点🥰

**Comment by kurisucat** [comment]
纯原生 JavaScript 是我目前会的，还不是很熟悉。

不用 Vue 等框架是因为我还不会，而且要有一定的 JavaScript 以及 TypeScript 水平，我刚刚说的两种语言我一个没掌握一个没学过。因此不考虑使用。

使用 Github Pages 是目前公开用来测试的，我的目的是这一套文件部署在哪里都可以使用。以后可能会用 CNAME 到 Github Pages 或者部署在服务器。

**Comment by FallenDoll** [comment]
Got it.
